package com.xbb.spring_jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

	public M setIconCls(java.lang.String iconCls) {
		set("iconCls", iconCls);
		return (M)this;
	}

	public java.lang.String getIconCls() {
		return getStr("iconCls");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setParentId(java.lang.String parentId) {
		set("parentId", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return getStr("parentId");
	}

	public M setPosition(java.lang.Integer position) {
		set("position", position);
		return (M)this;
	}

	public java.lang.Integer getPosition() {
		return getInt("position");
	}

}
